.PHONY: download
download:
# NOTE: cassandra 2.2 is using v4
# wget https://raw.githubusercontent.com/apache/cassandra/trunk/doc/native_protocol_v3.spec
	wget https://raw.githubusercontent.com/apache/cassandra/trunk/doc/native_protocol_v4.spec
	wget https://raw.githubusercontent.com/apache/cassandra/trunk/doc/native_protocol_v5.spec